"""add error grouping

Revision ID: 162f1f83988f
Revises: 1581eae12fa0
Create Date: 2026-07-22 10:48:35.227843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162f1f83988f'
down_revision: Union[str, Sequence[str], None] = '1581eae12fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "error_groups",
    sa.Column("id", sa.Integer(), primary_key=True),
    sa.Column("fingerprint", sa.String(64), nullable=False),
    sa.Column("occurrences", sa.Integer(), nullable=False),
    sa.Column(
        "first_seen",
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
    ),
    sa.Column(
        "last_seen",
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
    ),
    )
    op.create_index(
    op.f("ix_error_groups_fingerprint"),
    "error_groups",
    ["fingerprint"],
    unique=True,
    )
    op.add_column(
    "error_logs",
    sa.Column("group_id", sa.Integer(), nullable=True),
    )

    op.create_foreign_key(
    None,
    "error_logs",
    "error_groups",
    ["group_id"],
    ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        None,
        "error_logs",
        type_="foreignkey",
    )
    op.drop_column(
        "error_logs",
        "group_id",
    )
    op.drop_index(
        op.f("ix_error_groups_fingerprint"),
        table_name="error_groups",
    )
    op.drop_table("error_groups")