"""add auth fields to users

Revision ID: 8460a8b06c85
Revises: 202bf1631a82
Create Date: 2026-06-15 15:49:07.352324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8460a8b06c85"
down_revision: str | Sequence[str] | None = "202bf1631a82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    op.drop_table("users_alembic")
    op.drop_table("posts")
    op.drop_table("post_tags")
    op.drop_table("tags")
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "users", "name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "users", "email", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::text"),
    )
    op.drop_column("users", "created_at")
    op.drop_column("users", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::text"),
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.alter_column(
        "users", "email", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "users", "name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("tags_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("tags_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "post_tags",
        sa.Column("post_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("post_tags_post_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("post_tags_tag_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", "tag_id", name=op.f("post_tags_pkey")),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("posts_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("posts_pkey")),
    )
    op.create_table(
        "users_alembic",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("age", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_alembic_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("users_alembic_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("comments_post_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("comments_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comments_pkey")),
    )
    # ### end Alembic commands ###
