"""add audit_logs table

Revision ID: e31d2d472910
Revises: 8489fbbdd26b
Create Date: 2026-06-24 15:38:17.409151

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e31d2d472910'
down_revision: str | Sequence[str] | None = '8489fbbdd26b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
